### ISSUE TITLE
Commit #b5f279e (ipv6 branch) - Tor instance doesn't start with the script

### ISSUE THREAD

**Issue by ghost** [orjail/orjail#15]
>> https://github.com/torjail/torjail/commit/b5f279eceb5fcb7a2e7eb1884d41e1cf562ac8c8

I'm adding IPv6 support on torjail with a **--ipv6 | -6** option, but when I start the script, the Tor instance doesn't run together with it, I must hit **$ /usr/sbin/tor --quiet -f /tmp/torXXXXX** on a terminal windows for starting Tor.

What is wrong here?

**Comment by gibix** [comment]
I close this because @ghost is a deleted user and we can maintain the discussion on https://github.com/orjail/orjail/issues/12
