### ISSUE TITLE
Is it possible to pass firejail parameters from the torjail command line?

### ISSUE THREAD

**Issue by Futureknows** [orjail/orjail#17]
For instance, `--private --net=eth0 --machine-id`, or other per instance parameters to customize torjails?

**Comment by lesion** [comment]
this is actually not supported but should be easy to implement, take a look [here](https://github.com/torjail/torjail/blob/master/torjail#L468-L474)

**Comment by gibix** [comment]
closed with https://github.com/orjail/orjail/commit/f32fb25c19ff3410f9159c444b581c088d96f917
