### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by adrelanos** [orjail/orjail#20]
Could you clarify license please?

I am interested to package this tool for Whonix.

**Comment by lesion** [comment]
Hi Patrick,
This sounds interesting, also if I cannot see any use case of orjail inside whonix, as whonix does already the same job (and way better I'll say).

licence is [WTFPL](http://www.wtfpl.net) now (GPL compatible)

**Comment by adrelanos** [comment]
Hi lesion,
thanks for your quick clarification!

We are [considering](https://forums.whonix.org/t/managing-programs-without-tor-dns-support/4840/14) how we could add [stream isolation](https://www.whonix.org/wiki/Stream_Isolation) to applications that are not easily stream isolated by dropping proxy settings into a `.d` folder.

Currently we are using [uwt](https://github.com/Whonix/uwt) which is a wrapper around torsocks. orjail may be providing stronger isolation. Modifications are required to make orjail work in Whonix. We wouldn't start Tor instances on Whonix-Workstation but rather point to pre-configured Tor `TransPort`s / `DnsPort`s opened on Whonix-Gateway.

**Comment by gibix** [comment]
I think is a good use case, can you please open a dedicated issue?

**Comment by adrelanos** [comment]
Sure, created https://github.com/orjail/orjail/issues/23 for it.
