### ISSUE TITLE
add stream isolation support

### ISSUE THREAD

**Issue by adrelanos** [orjail/orjail#23]
* `TransPort` is currently hardcoded to `9040`
* `DnsPort` is currently hardcoded to `5354`

It would be good to make that configurable.

By using distinct `TransPort` / `DnsPort` ports per application you would gain stream isolation.

`torsocks` supports `IsolatePID`.

```
# Set Torsocks to use an automatically generated SOCKS5 username/password based
# on the process ID and current time, that makes the connections to Tor use a
# different circuit from other existing streams in Tor on a per-process basis.
# If set, the SOCKS5Username and SOCKS5Password options must not be set.
# (Default: 0)
IsolatePID 1
```

Which then results in using Tor's [`IsolateSOCKSAuth`](https://www.torproject.org/docs/tor-manual.html.en).

>Don’t share circuits with streams for which different SOCKS authentication was provided. (For HTTPTunnelPort connections, this option looks at the Proxy-Authorization and X-Tor-Stream-Isolation headers. On by default; you can disable it with NoIsolateSOCKSAuth.)

`TransPort` / `DnsPort` doesn't support user auth credentials which would lead to stream isolation so the only way is to use distinct ports.

**Comment by gibix** [comment]
Could be useful to have a random port selector? I want to establish circuit isolation but I don't care about witch port is used, this because could be quite a pain to specify every time two open ports.

**Comment by adrelanos** [comment]
Yes, it could pick from a predefined (configurable through variable in
script) port range.

(For Whonix / uwt we'd need to define which port to use using an
environment variable (preferred) or command line option - but that part
is simple, could provide a patch later.)

**Comment by gibix** [comment]
We are running out of short flag, so I think is time to have longer ones.
```
--port-range
--trans-port
--dns-port
```

**Comment by gibix** [comment]
closed with https://github.com/orjail/orjail/commit/73cf6545063c7ca0d46ffb984b8107b9dd3e678e
