### ISSUE TITLE
exit with exit code of the application / use cleanup trap

### ISSUE THREAD

**Issue by adrelanos** [orjail/orjail#29]
```
# use firejail as security container
if [ $USEFIREJAIL = y ]; then
  if [ "$SUDOBIN" ]; then
    $SUDOBIN -u "$USERNAME" "$FIREJAILBIN" "${FIREJAILARGS[@]}" --dns="$IPHOST" --netns="$NAME" "$@"
  else
    su "$USERNAME" -c "$FIREJAILBIN ${FIREJAILARGS[*]} --dns=$IPHOST --netns=$NAME $*"
  fi
else #or without
  ip netns exec "$NAME" \
    unshare --ipc --fork --pid --mount --mount-proc \
    "$0" --inside "$USERNAME" "$RESOLVEFILE" "$VERBOSE" "$@" || \
    die "Failed to execute the inside part of this script"
fi

# clean some shit
cleanup

# All done!
```

Running `cleanup` by writing `cleanup` at the end leads to the exit code of the application being forgotten. Using...

    trap "cleanup" EXIT

would be much nicer. That way your cleanup code gets run on any termination as well as you don't need something like `exit_code=$?`, `exit $exit_code`.

Why? This would be useful for use use in scripts. A wrapper should interfere with the wrapped application as little as possible, i.e. no extraneous output in most cases (unless debug, unless some special error) and forwarding the exit code of the wrapped application.

**Comment by lesion** [comment]
closed via #32
