### ISSUE TITLE
support for ephemeral Tor hidden services / local listener support / onionshare

### ISSUE THREAD

**Issue by adrelanos** [orjail/orjail#36]
onionshare

https://onionshare.org/

https://github.com/micahflee/onionshare/raw/develop/screenshots/server.png

* uses ephemeral Tor onion services
* it creates a local listener (mini http server serving the file to be shared)

----

ephemeral Tor onion services

* This basically means, that it uses the Tor ControlProtocol to create the hidden service. Not using torrc modifications.
 * Yes, ephemeral Tor hidden services can also persist between application starts. After creating it with add_onion new, you get the hidden service private key, can store it, and restore it later.
 * This can be done using python-stem. - https://packages.debian.org/stretch/python3-stem

----

`sudo orjail -y onionshare COPYING `
```
Onionshare 1.3 | https://onionshare.org/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/onionshare/common.py", line 208, in get_available_port
    tmpsock.bind(("127.0.0.1", random.randint(min_port, max_port)))
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 193, in connect
    self.tor_socks_port = common.get_available_port(1000, 65535)
  File "/usr/lib/python3/dist-packages/onionshare/common.py", line 211, in get_available_port
    raise OSError(e)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/onionshare", line 22, in <module>
    onionshare.main()
  File "/usr/lib/python3/dist-packages/onionshare/__init__.py", line 86, in main
    onion.connect(settings=False, config=config)
  File "/usr/lib/python3/dist-packages/onionshare/onion.py", line 195, in connect
    raise OSError(strings._('no_available_port'))
OSError: Could not start the Onion service as there was no available port
```

**Comment by lesion** [comment]
the first issue here is that inside orjail namespace there's no 127.0.0.1 / lo interface, and I suppose this is causing the error:
```
tmpsock.bind(("127.0.0.1", random.randint(min_port, max_port)))
OSError: [Errno 99] Cannot assign requested address
```
the second issue I see is that onionshare will probably try to talk to tor via the same localhost address, but the tor instance of orjail is launched outside his network namespace (so will have another address).

I've found this discussion about similar stuff:
https://github.com/micahflee/onionshare/issues/27
https://github.com/micahflee/onionshare/issues/220

so quoting you:
> We at Whonix yet have to find a solution to this issue:
> find way to have Tor ephermal hidden service using applications in Whonix-Workstation bind on all interfaces
> I.e. onionshare binds its webserver on 127.0.0.1. In Whonix, that cannot work because it needs to bind on the external IP.
