### ISSUE TITLE
combine with torsocks good idea?

### ISSUE THREAD

**Issue by adrelanos** [orjail/orjail#40]
Would it make sense to add torsocks to the execution anyhow? To make it "even more leak proof"? `--torsocks`?

It could be more leak proof since using torsocks but also having higher attack surface since involving torsocks's C code?

Or would that be nonsense?

**Comment by lesion** [comment]
I don't really see the sense :/

**Comment by adrelanos** [comment]
Alright, let's forget about it unless someone else has an actual argument. :)
