### ISSUE TITLE
orjail leaks non-TCP/Tor packets if forwarding is enabled in the main OS.

### ISSUE THREAD

**Issue by phantomcraft** [orjail/orjail#43]
IP forwarding is needed to be activated sometimes.

When net.ipv4.conf.all.forwarding and net.ipv4.conf.default.forwarding are enabled (with sysctl), all non-Tor packets are visible in the main network stack coming from orjail, that is, the internal packets inside sandbox.

I really don't know if the packets leaks through router and reaches the Internet IP which is destined, but if there is an adversary controlling the router, yes, he can capture all of them!

$ orjail -v -u root ping 1.1.1.1
$ orjail -v deluge magnet:?xt=urn:btih:f4e3cc2db4163e3b1ff77b3e23b76b85a1d4ee1f&tr=https://ipleak.net/announce.php%3Fh%3Df4e3cc2db4163e3b1ff77b3e23b76b85a1d4ee1f&dn=ipleak.net+torrent+detection # Torrent leak test from ipleak.net

Running tcpdump show this:

$ tcpdump -vv -i in-orjail | grep 10.200.1.2

Running inside a separate namespace prove that the main router can see the leaked packets:

$ ip netns add nsx
$ ip link add vethx type veth peer name peerx
$ ip link set peerx netns nsx
$ ip addr add 10.100.1.1/24 dev vethx
$ ip link set vethx up
$ ip netns exec nsx ip addr add 10.100.1.2/24 dev peerx
$ ip netns exec nsx ip li set peerx up
$ ip netns exec nsx ip route add default via 10.100.1.1 dev peerx
$ iptables -t nat POSTROUTING -s 10.100.1.0/24 -o eth0 -j MASQUERADE
$ ip netns exec nsx orjail -s -u root ping 1.1.1.1

$ tcpdump -vv -i in-orjail | grep 10.200.1.2
$ tcpdump -vv -i eth0 | grep 10.200.1.2

Yes, leaked packets pass through virtual interface vethx from the network namespace nsx and reaches the upside router.

There is a simple fix for this:

$ iptables -I FORWARD 1 -i in-orjail -j DROP
$ iptables -I FORWARD 1 -o in-orjail -j DROP
$ sysctl -w -q net.ipv4.conf.in-orjail.forwarding=0

Now none of the packets leaks.

Some additional iptables rules for protection:

$ iptables -t nat -I POSTROUTING 1 \! -o in-orjail -s 10.200.1.0/24 -j RETURN
$ iptables -t nat -I PREROUTING 1 \! -i in-orjail -d 10.200.1.0/24 -j RETURN

$ iptables -t nat -A PREROUTING -i in-torjail -j RETURN

$ iptables -A INPUT \! -i in-orjail -s 10.200.1.0/24 -j DROP
$ iptables -A INPUT \! -i in-orjail -d 10.200.1.0/24 -j DROP

**Comment by phantomcraft** [comment]
This issue needs urgent attention, I used orjail for almost 1 year since it was torjail, although I never made anything illegal with it.

**Comment by lesion** [comment]
thanks, I'm looking on it

**Comment by lesion** [comment]
Very nice catch!
Fixed as suggested, thanks.

Before adding the additional rules I want to investigate a bit more, so I leave this issue open for now.

**Comment by phantomcraft** [comment]
@lesion

There is some programs that adds netfilter rules without user knows that (as Guidedog does), and also, the user may want to have some iptables rules saved for loading in system initialization. Is possible to these rules conflict with those of orjail and lead to a potential leak.

Everything coming from orjail (-s 10.200.1.0/24) will not reach any other interface but orjail (! -o orjail), being the first in the chain will block everything down:
$ iptables -t nat -I POSTROUTING 1 \! -o in-orjail -s 10.200.1.0/24 -j RETURN

Redirections from orjail (10.200.1.0/24) will not reach anything but orjail (! -i in-orjail) being the fist in the chain:
$ iptables -t nat -I PREROUTING 1 \! -i in-orjail -d 10.200.1.0/24 -j RETURN

This will prevent any other port redirection to me made in the orjail virtual interface, must be appended (-A) after all other DNAT rules (remember, some programs listen on 0.0.0.0 and [::], and so, will listen on the orjail veth too!):
$ iptables -t nat -A PREROUTING -i in-orjail -j RETURN

This will prevent pings on the orjail veth (if there is an adversary controlling the internet router (gateway),  he can ping orjail)
$ iptables -A INPUT ! -i in-orjail -s 10.200.1.0/24 -j DROP
$ iptables -A INPUT ! -i in-orjail -d 10.200.1.0/24 -j DROP

The main purpose of this rules is lock orjail completely from the main network stack and prevent even the minor leaks.

Is very important that forwarding rules for orjail be the first in the chain, because they will neutralize all the other rules down in the chain. I suggest to put 1 (one) after FORWARD in the script as that:

iptables -I FORWARD 1 -i in-orjail -j DROP
iptables -I FORWARD 1 -o in-orjail -j DROP

**Comment by phantomcraft** [comment]
I think I leaked my real IP some months ago due to a very strange bug in the system which zeroed all my iptables rules. I decided to make a script for personal to achieve a paranoid level of isolation, I will share with you: https://gist.github.com/phantomcraft/2e7c3dfab8cf62702e784a8c54686fc8

Perhaps you can help to improve orjail.

**Comment by lesion** [comment]
Thank you for taking the time to explain.

> Is very important that forwarding rules for orjail be the first in the chain, because they will neutralize all the other rules down in the chain. I suggest to put 1 (one) after FORWARD in the script as that:

with -I if not specified 1 is the default value.

> I think I leaked my real IP some months ago due to a very strange bug in the system which zeroed all my iptables rules.

I'm really sorry to hear that. if you can, could you explain some details?

<  I decided to make a script for personal to achieve a paranoid level of isolation, I will share with you: https://gist.github.com/phantomcraft/2e7c3dfab8cf62702e784a8c54686fc8

It looks amazing, I think I'm going to study it a bit :smile:  
thanks

**Comment by phantomcraft** [comment]
@lesion 

I use Debian testing, I was using torjail when some strange bug zeroed all the iptables rules, I'm sure this was not a bug in orjail, but in the system. That's why I wrote that script.
