### ISSUE TITLE
Suggestion: Quickly clean all orjail iptables rules

### ISSUE THREAD

**Issue by phantomcraft** [orjail/orjail#44]
for nf_cmd in 'iptables' 'iptables -t nat'; do
  $nf_cmd -S | grep "in-$NAME" | while read line; do $nf_cmd ${line//-A/-D} &>/dev/null; done
done

^^ Less lines of code.

grep is omnipresent in linux distributions, it shouldn't be a problem.

**Comment by gibix** [comment]
Beautiful! Can you make a pull request yourself?
