### ISSUE TITLE
Orjail with Firejail bridged network

### ISSUE THREAD

**Issue by 4234234234234** [orjail/orjail#50]
Firejail uses a[ bridge network](https://firejail.wordpress.com/documentation-2/basic-usage/#routed) to create net namespace on wifi adapters. On my system, this bypasses orjail's Tor TUN which renders Firejail unusable with orjail on a WIFI adapter.

Is there any simple work around?

**Comment by lesion** [comment]
I don't know any difference between wifi adapters interface and others in this context, we don't use `--net` firejail's flag but `--netns` instead, joining an already created namespace attached to a `veth` interface orjail creates by itself. so I guess if you can navigate from your host throught your adapter interface I don't see any reason why this cannot work inside `orjail`.
You can try to experiment with firejail flags with `--firejail-args`.

**Comment by 4234234234234** [comment]
Solved. For some reason a `--firejail-args `got it to work, even though the same arg was already specified in the profile. With specifiying --firejail-args on orjail the app refused to launch with the following error code:

`/bin/bash: : command not found`

Solved!
