### ISSUE TITLE
README is missing how to install the script, make file fails

### ISSUE THREAD

**Issue by gdamdam** [orjail/orjail#51]
In the readme are missing the instructions about how to install the script.

Running make, it returns the error:
``
$ make
Makefile:21: /usr/share/genmkfile/makefile-full: No such file or directory
make: *** No rule to make target '/usr/share/genmkfile/makefile-full'.  Stop.
``

**Comment by lesion** [comment]
@adrelanos I'm trying to fix this issue and I've prepared a [section in the README](https://github.com/orjail/orjail#install) but I'll need some help. The point is, I do not want users to download another dependency (genmkfile) to install a bash script and I do not want to support debian only. Do you have any suggestion?

**Comment by adrelanos** [comment]
Yes. genmkfile can be standalone.

You can replace/add these two files in your repository root folder.

* https://github.com/adrelanos/vpn-firewall/blob/master/Makefile
* https://github.com/adrelanos/vpn-firewall/blob/master/make-helper.bsh
