### ISSUE TITLE
Permission Denied on tor socket error

### ISSUE THREAD

**Issue by zordtk** [orjail/orjail#78]
I installed from the debian package and receive the following error:

```

sudo orjail -v ifconfig
 * 10.200.254.2 <---> 10.200.254.1
 * Creating a orjail namespace...
 * Creating a veth link...
 * Sharing the veth interface...
 * Setting up IP address of host interface (10.200.254.2/30)
 * Setting up IP address of peer interface (10.200.254.1/30)
 * Default routing up...
 * Bringing orjail loopback up...
 * Resolving via Tor
 * Traffic via Tor...
 * Creating the Tor configuration file...
 * Tor version is 0.4.5.6.
/usr/sbin/orjail: line 550: /tmp/torjnV50q: Permission denied
[Error] in command: cat >> "$TORCONFIGFILE" <<EOF
  DataDirectory /tmp/orjail-${NAME}
  AutomapHostsSuffixes .onion,.exit
  AutomapHostsOnResolve 1
  PidFile      /tmp/orjail-${NAME}/pid
  User         ${USERNAME}
  VirtualAddrNetworkIPv4 ${IPNETNS}/16
  TransPort ${IPHOST}:${TRANSPORT}
  DNSPort ${IPHOST}:${DNSPORT}
  SOCKSPort 0
  RunAsDaemon 1
EOF

 * Remove Tor temporary configuration
 * Killing Tor process 
 * Killed 
 * Remove Tor DataDirectory: /tmp/orjail-orjail
 * Remove in-orjail network interface
 * Delete network namespace orjail
 * Cleaning up iptables rules...
```

**Comment by ExceptionGit** [comment]
User does not have permission to write in /tmp ?

**Comment by phantomcraft** [comment]
Your /tmp folder has incorrect permissions, change it:

**_sudo chmod -R 1777 /tmp_**

**Comment by zordtk** [comment]
This is a fresh Ubuntu 21.04 and my /tmp directory is already set to 1777

```
  File: /tmp
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 10303h/66307d	Inode: 12713985    Links: 37
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-06-22 13:06:54.807709934 -0400
Modify: 2021-06-22 20:19:52.547566597 -0400
Change: 2021-06-22 20:19:52.547566597 -0400
 Birth: 2021-06-02 18:16:42.695260375 -0400

```

**Comment by zordtk** [comment]
It also fails the same way if I run it as root without SUDO

**Comment by jairomer** [comment]
It worked for me by login in with 'su' first, then executing 'orjail' within.
It is clear that the effects of 'sudo' and 'su' change depending on the distro and the kernel version.

I am running Manjaro with kernel 5.10.42-1

A way to get this to work would then be something like:
`su -c "orjail curl checkip.amazonaws.com"

**Comment by onny** [comment]
I'm trying to package `orjail` for NixOS ( https://github.com/NixOS/nixpkgs/pull/138293 ) and I also get this error :(

**Comment by lesion** [comment]
Could you please try avoidTmp branch ?
thanks for reporting

**Comment by onny** [comment]
I fixed it by using `mktemp torXXX` instead of `mktemp /tmp/torXXX`

**Comment by lesion** [comment]
> I fixed it by using `mktemp torXXX` instead of `mktemp /tmp/torXXX`
Doing so you don't have any other issues?
This is strange because we use /tmp also for other things (eg. https://github.com/orjail/orjail/blob/master/usr/sbin/orjail#L594 )

**Comment by onny** [comment]
> > I fixed it by using `mktemp torXXX` instead of `mktemp /tmp/torXXX`
> 
> Doing so you don't have any other issues?
> This is strange because we use /tmp also for other things (eg. https://github.com/orjail/orjail/blob/master/usr/sbin/orjail#L594 )

I don't have any permission issues with `/tmp` but somehow with mktemp using it like this. Please note that this affects me on NixOS which is kind of a special OS ^^

**Comment by zordtk** [comment]
Can also confirm this fixes it on Ubuntu. Thanks
