### ISSUE TITLE
Cannot locate bc executable

### ISSUE THREAD

**Issue by ThomasEH2005** [orjail/orjail#89]
Hi i always get an error i dont really understand.

Cannot locate bc executable
[Error] in command: exit $err
 * Remove Tor temporary configuration
 * Killing Tor process 
 * Killed 
 * Remove Tor DataDirectory: /tmp/orjail-orjail
 * Remove in-orjail network interface
Cannot find device "in-orjail"
 * Delete network namespace orjail
Cannot remove namespace file "/run/netns/orjail": No such file or directory
 * Cleaning up iptables rules...

**Comment by phantomcraft** [comment]
You should install the program **bc** in the package manager of your Linux distribution.

In Debian/Ubuntu/Linux Mint is easy as:

`sudo apt-get install bc`
